// Code generated by @regox/vite-plugin. DO NOT EDIT.
package regoxroutes

import (
	"context"

	"github.com/a-h/templ"
	server "regox.dev/server"
	"regox.dev/mvp/generated"
	"regox.dev/mvp/templates"
)

// Route patterns in Go ServeMux format.
// CSR routes are auto-registered by RegisterRoutes via AutoRegisterCSR.
// SSR/ISR routes call the matching PageResolvers method.
const (
	RouteCart = "/cart" // csr — auto-registered
	RouteHome = "/" // ssr
	RouteProductsId = "/products/{id}" // ssr
	RouteProducts = "/products" // isr — revalidate: 60s
)

// PageModes maps each route constant to its rendering mode.
var PageModes = map[string]string{
	RouteCart: "csr",
	RouteHome: "ssr",
	RouteProductsId: "ssr",
	RouteProducts: "isr",
}

// PageResolvers provides data for all SSR and ISR pages.
// Implement this interface and pass it to RegisterRoutes.
type PageResolvers interface {
	HomePage(ctx *server.RequestCtx) (any, error)
	ProductDetailPage(ctx *server.RequestCtx) (any, error)
	ProductsPage(ctx *server.RequestCtx) (any, error)
}

// RegisterRoutes wires all pages from the manifest.
// SSR/ISR pages call the matching method on resolvers for each request.
// CSR pages are pre-rendered shells that include island mount points.
func RegisterRoutes(r *server.Router, resolvers PageResolvers) error {
	r.SSR(RouteHome, func(ctx context.Context, data any) (templ.Component, error) {
		return templates.HomePage(data.(generated.HomePageData)), nil
	}, func(ctx *server.RequestCtx) (any, error) {
		return resolvers.HomePage(ctx)
	})
	r.SSR(RouteProductsId, func(ctx context.Context, data any) (templ.Component, error) {
		return templates.ProductDetailPage(data.(generated.ProductDetailPageData)), nil
	}, func(ctx *server.RequestCtx) (any, error) {
		return resolvers.ProductDetailPage(ctx)
	})
	r.ISR(RouteProducts, func(ctx context.Context, data any) (templ.Component, error) {
		return templates.ProductsPage(data.(generated.ProductsPageData)), nil
	}, func(ctx *server.RequestCtx) (any, error) {
		return resolvers.ProductsPage(ctx)
	})
	if err := r.CSRPage(RouteCart, templates.CartPage()); err != nil {
		return err
	}
	return nil
}
