import { describe, it, expect } from 'vitest'
import { generateGoRoutes } from '../go-routes-writer.ts'
import type { PageMeta } from '../types.ts'

function fakePage(route: string, mode: PageMeta['mode'], revalidate?: number): PageMeta {
  const seg = route === '/' ? 'Home' : route.replace(/^\//, '').replace(/\/\[.+\]$/, '').split('/').map(s => s[0].toUpperCase() + s.slice(1)).join('')
  return {
    filePath: `/pages${route === '/' ? '/index' : route}.tsx`,
    route,
    mode,
    revalidate,
    pageName: seg + 'Page',
    dataType: null,
    templPath: '',
    propsPath: '',
  }
}

describe('generateGoRoutes', () => {
  it('includes a code-generated header', () => {
    const out = generateGoRoutes([], 'generated')
    expect(out).toContain('Code generated by @regox/vite-plugin')
    expect(out).toContain('DO NOT EDIT')
  })

  it('emits the correct package declaration', () => {
    expect(generateGoRoutes([], 'mypkg')).toContain('package mypkg')
  })

  it('generates a const block for each page', () => {
    const pages = [fakePage('/', 'ssr'), fakePage('/cart', 'csr')]
    const out = generateGoRoutes(pages, 'generated')
    expect(out).toContain('RouteHome')
    expect(out).toContain('RouteCart')
  })

  it('converts [param] to {param} in route values', () => {
    const pages = [fakePage('/products/[id]', 'ssr')]
    const out = generateGoRoutes(pages, 'generated')
    expect(out).toContain('"/products/{id}"')
  })

  it('annotates CSR routes as auto-registered', () => {
    const pages = [fakePage('/cart', 'csr')]
    const out = generateGoRoutes(pages, 'generated')
    expect(out).toContain('csr')
    expect(out).toContain('auto-registered')
  })

  it('annotates ISR routes with revalidate seconds', () => {
    const pages = [fakePage('/products', 'isr', 60)]
    const out = generateGoRoutes(pages, 'generated')
    expect(out).toContain('revalidate: 60s')
  })

  it('uses RouteHome for the root route', () => {
    const pages = [fakePage('/', 'ssr')]
    const out = generateGoRoutes(pages, 'generated')
    expect(out).toContain('RouteHome')
    expect(out).toContain('"/"')
  })

  it('generates a PageModes var mapping routes to modes', () => {
    const pages = [fakePage('/', 'ssr'), fakePage('/cart', 'csr')]
    const out = generateGoRoutes(pages, 'generated')
    expect(out).toContain('PageModes')
    expect(out).toContain('"ssr"')
    expect(out).toContain('"csr"')
  })
})

describe('generateGoRoutes with goModule (full wiring)', () => {
  const opts = { goModule: 'regox.dev/mvp' }

  it('imports templates and server packages', () => {
    const pages = [{ ...fakePage('/', 'ssr'), pageName: 'HomePage' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).toContain('"regox.dev/mvp/templates"')
    expect(out).toContain('server "regox.dev/server"')
  })

  it('generates PageResolvers interface', () => {
    const pages = [{ ...fakePage('/', 'ssr'), pageName: 'HomePage' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).toContain('PageResolvers')
    expect(out).toContain('HomePage(ctx *server.RequestCtx) (any, error)')
  })

  it('omits CSR pages from PageResolvers', () => {
    const pages = [{ ...fakePage('/cart', 'csr'), pageName: 'CartPage' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).not.toContain('CartPage(ctx context.Context')
  })

  it('generates RegisterRoutes with r.SSR for SSR pages', () => {
    const pages = [{ ...fakePage('/', 'ssr'), pageName: 'HomePage' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).toContain('func RegisterRoutes(')
    expect(out).toContain('r.SSR(')
    expect(out).toContain('templates.HomePage(')
    expect(out).toContain('.(generated.HomePageData)')
  })

  it('generates r.ISR for ISR pages', () => {
    const pages = [{ ...fakePage('/products', 'isr', 60), pageName: 'ProductsPage' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).toContain('r.ISR(')
  })

  it('registers CSR pages with r.CSRPage in RegisterRoutes', () => {
    const pages = [{ ...fakePage('/cart', 'csr'), pageName: 'CartPage' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).toContain('r.CSRPage(RouteCart, templates.CartPage())')
  })

  it('uses explicit dataType when provided', () => {
    const pages = [{ ...fakePage('/product/[id]', 'ssr'), pageName: 'ProductPage', dataType: 'ProductPageData' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).toContain('.(generated.ProductPageData)')
  })

  it('uses pageName+Data convention when dataType is null', () => {
    const pages = [{ ...fakePage('/', 'ssr'), pageName: 'HomePage', dataType: null }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).toContain('.(generated.HomePageData)')
  })

  it('skips routes starting with underscore', () => {
    const pages = [{ ...fakePage('/_layout', 'csr'), pageName: 'Layout' }]
    const out = generateGoRoutes(pages, 'regoxroutes', opts)
    expect(out).not.toContain('RouteLayout')
    expect(out).not.toContain('/_layout')
  })
})
