import fs from 'node:fs'
import path from 'node:path'
import type { PageMeta } from './types.ts'

export interface GoCodegenOptions {
  goModule?: string
}

function manifestRouteToGoPattern(route: string): string {
  return route.replace(/\[([^\]]+)\]/g, '{$1}')
}

function routeToConstName(route: string): string {
  if (route === '/') return 'RouteHome'
  return (
    'Route' +
    route
      .replace(/^\//, '')
      .split('/')
      .map(seg => {
        const clean = seg.replace(/[\[\]{}]/g, '')
        return clean.charAt(0).toUpperCase() + clean.slice(1)
      })
      .join('')
  )
}

function modeAnnotation(page: PageMeta): string {
  if (page.mode === 'csr') return 'csr — auto-registered'
  if (page.mode === 'isr' && page.revalidate != null) return `isr — revalidate: ${page.revalidate}s`
  return page.mode
}

function isSpecialRoute(route: string): boolean {
  return route.split('/').some(seg => seg.startsWith('_'))
}

function effectiveDataType(page: PageMeta): string {
  return page.dataType ?? page.pageName + 'Data'
}

function generateImports(goModule: string): string {
  return [
    'import (',
    '\t"context"',
    '\t"net/http"',
    '',
    '\t"github.com/a-h/templ"',
    `\tserver "regox.dev/server"`,
    `\t"${goModule}/generated"`,
    `\t"${goModule}/templates"`,
    ')',
  ].join('\n')
}

function generatePageResolvers(pages: PageMeta[]): string {
  const serverPages = pages.filter(p => p.mode === 'ssr' || p.mode === 'isr')
  if (serverPages.length === 0) return ''
  const lines = ['// PageResolvers provides data for all SSR and ISR pages.', '// Implement this interface and pass it to RegisterRoutes.', 'type PageResolvers interface {']
  for (const page of serverPages) {
    lines.push(`\t${page.pageName}(ctx context.Context, req *http.Request) (any, error)`)
  }
  lines.push('}')
  return lines.join('\n')
}

function generateRegisterRoutes(pages: PageMeta[]): string {
  const lines = [
    '// RegisterRoutes wires all pages from the manifest.',
    '// SSR/ISR pages call the matching method on resolvers for each request.',
    '// CSR pages are served as static HTML shells via AutoRegisterCSR.',
    'func RegisterRoutes(r *server.Router, resolvers PageResolvers) error {',
  ]

  // Suppress unused import error when no server pages exist
  const serverPages = pages.filter(p => p.mode === 'ssr' || p.mode === 'isr')
  if (serverPages.length === 0) {
    lines.push('\t_ = templ.ComponentFunc(nil)')
  }

  for (const page of pages.filter(p => p.mode === 'ssr')) {
    const dt = effectiveDataType(page)
    const constName = routeToConstName(page.route)
    lines.push(
      `\tr.SSR(${constName}, func(ctx context.Context, data any) (templ.Component, error) {`,
      `\t\treturn templates.${page.pageName}(data.(generated.${dt})), nil`,
      `\t}, func(ctx context.Context, req *http.Request) (any, error) {`,
      `\t\treturn resolvers.${page.pageName}(ctx, req)`,
      `\t})`,
    )
  }
  for (const page of pages.filter(p => p.mode === 'isr')) {
    const dt = effectiveDataType(page)
    const constName = routeToConstName(page.route)
    lines.push(
      `\tr.ISR(${constName}, func(ctx context.Context, data any) (templ.Component, error) {`,
      `\t\treturn templates.${page.pageName}(data.(generated.${dt})), nil`,
      `\t}, func(ctx context.Context, req *http.Request) (any, error) {`,
      `\t\treturn resolvers.${page.pageName}(ctx, req)`,
      `\t})`,
    )
  }

  lines.push('\treturn r.AutoRegisterCSR()')
  lines.push('}')
  return lines.join('\n')
}

export function generateGoRoutes(
  pages: PageMeta[],
  goPackage: string,
  opts?: GoCodegenOptions,
): string {
  const visiblePages = pages.filter(p => !isSpecialRoute(p.route))

  const lines: string[] = [
    '// Code generated by @regox/vite-plugin. DO NOT EDIT.',
    `package ${goPackage}`,
    '',
  ]

  if (opts?.goModule) {
    lines.push(generateImports(opts.goModule))
    lines.push('')
  }

  if (visiblePages.length > 0) {
    lines.push('// Route patterns in Go ServeMux format.')
    lines.push('// CSR routes are auto-registered by RegisterRoutes via AutoRegisterCSR.')
    lines.push('// SSR/ISR routes call the matching PageResolvers method.')
    lines.push('const (')
    for (const page of visiblePages) {
      const constName = routeToConstName(page.route)
      const pattern = manifestRouteToGoPattern(page.route)
      lines.push(`\t${constName} = "${pattern}" // ${modeAnnotation(page)}`)
    }
    lines.push(')')
    lines.push('')

    lines.push('// PageModes maps each route constant to its rendering mode.')
    lines.push('var PageModes = map[string]string{')
    for (const page of visiblePages) {
      const constName = routeToConstName(page.route)
      lines.push(`\t${constName}: "${page.mode}",`)
    }
    lines.push('}')
  }

  if (opts?.goModule && visiblePages.length > 0) {
    lines.push('')
    lines.push(generatePageResolvers(visiblePages))
    lines.push('')
    lines.push(generateRegisterRoutes(visiblePages))
  }

  return lines.join('\n') + '\n'
}

export function writeGoRoutes(
  pages: PageMeta[],
  outDir: string,
  goPackage: string,
  opts?: GoCodegenOptions,
): void {
  fs.mkdirSync(outDir, { recursive: true })
  fs.writeFileSync(
    path.join(outDir, 'routes.go'),
    generateGoRoutes(pages, goPackage, opts),
    'utf-8',
  )
}
